export const GET_PICS_REQUEST = 'GET_PICS_REQUEST';
export const GET_PICS_SUCCESS = 'GET_PICS_SUCCESS';
export const GET_PICS_FAILURE = 'GET_PICS_FAILURE';

export const CHOOSE_PICTURE = 'CHOOSE_PICTURE';